name: to_do_list_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.1.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  get_it: ^9.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  lottie: ^3.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/icons/

